name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [10]
    steps:
    - uses: actions/checkout@v2
    - name: Build web and then the Docker image
      run: |
        npm ci
        npm run build
        docker build . --file Dockerfile --tag sebastianandreas/gurka-web:${{ github.sha }}
      working-directory: web
